version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Yarn
          command: npm install -g yarn@~1.22.0

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Build
          command: npm run frontend-build

  test:
    docker:
      - image: circleci/node:14.17
    working_directory: ~/repo

    steps:
      - checkout

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
