version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build app
          command: yarn build
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Lint code
          command: yarn lint
